---

defaults:
  type: vega
  flux: 18 mag(AB)
  wavelength_band: K
  redshift: 2.0  # negative for blueshift

source_types:

  emission:
    name: Emission Line
    parameters:
      width: 200 nm

  blackbody:
    name: Blackbody
    parameters:
      temperature: 5000 K

  power:
    name: Power Law
    parameters:
      index: -2

  flat:
    name: Flat

  vega:
    name: Vega
    filename: vega_template.txt

  qso:
    name: QSO
    filename: qso_template.txt

  seyfert1:
    name: Seyfert 1
    filename: seyfert1_template.txt

  seyfert2:
    name: Seyfert 2
    filename: seyfert2_template.txt

# Path (absolute or relative) to directory containing source template files
template_filepath: calculator/source/

# Source for flux of vega, used to define mag(vega) as a unit
vega_filename: vega_template.txt

# List of wavelength bands and their central wavelength, edit to change available options
wavelength_band_options:
  U: 365 nm
  B: 445 nm
  G: 464 nm
  V: 551 nm
  R: 658 nm
  I: 806 nm
  Z: 900 nm
  Y: 1020 nm
  J: 1220 nm
  H: 1630 nm
  K: 2190 nm
  L: 3450 nm
  M: 4750 nm
  N: 10500 nm
  Q: 21000 nm